name: Build and Cache Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: my-image:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false # set to true if you want to push the image